# -*- coding: utf-8 -*-
"""Contenido del mapa de usuario y validación · Rehavid Gestión de proyectos v12.
Segunda ronda: usuarios por cargo, sin nombres de persona."""

PASOS = {
    1: "Paso 1-2 · Venta y registro obligatorio",
    3: "Paso 3 · Validación y activación",
    4: "Paso 4-5 · Asignación automática y tareas",
    6: "Paso 6 · Aceptación y negociación de capacidad",
    7: "Paso 7 · Requisitos de información y contacto",
    8: "Paso 8 · Plan de trabajo final",
    9: "Paso 9 · Ejecución y actualización",
    10: "Paso 10 · Producto completado y cierre",
    11: "Paso 11 · Cierre del proyecto maestro",
    12: "Transversal · consulta y control",
}

ORDEN_ROLES = [
    ("CEO", "CEO"),
    ("Gerente", "Gerente"),
    ("Director de Proyectos", "Director de Proyectos"),
    ("Jefe de Operaciones", "Jefe de Operaciones"),
    ("Supervisor Contactabilidad", "Supervisor Contactabilidad"),
    ("Gestor de Datos 1", "Gestor de Datos 1"),
    ("Gestor de Datos 2", "Gestor de Datos 2"),
    ("Diseñador", "Diseñador"),
]

ROLES = {

"CEO": dict(nombre="CEO", responsabilidad=(
    "Dirección general. Puede generar nuevos proyectos (RN-01), resolver ajustes como dirección, "
    "parametrizar y consultar todo el portafolio."), filas=[
 (1, "Generar un nuevo proyecto como CEO",
  "Entre en sesión como CEO (selector superior derecho). Abra 07 Nuevo proyecto. Verifique que Vendedor, "
  "Cargo del vendedor y Fecha de venta aparecen bloqueados con su cargo. Diligencie empresa y PPR del catálogo, "
  "tipo, plan estimado y observaciones de la venta; agregue un producto con horas y fecha solicitada, y el contacto principal completo.",
  "El vendedor queda amarrado a la sesión CEO sin poder editarse; el asistente permite avanzar los cuatro pasos."),
 (3, "Verificar el bloqueo por datos fuera de catálogo",
  "En el paso 1 escriba una empresa que no exista en el catálogo y avance al paso 4 de validaciones.",
  "La validación «Empresa y PPR del catálogo parametrizado» aparece en rojo y el botón de activar queda deshabilitado."),
 (3, "Activar un proyecto completo",
  "Corrija la empresa, complete lo pendiente y pulse Activar en el paso 4.",
  "Las 14 validaciones quedan en verde, el proyecto pasa a Activo y se generan las asignaciones por cargo con sus tareas."),
 (4, "Revisar las tareas que generó el motor",
  "Abra 09 Bases y auditoría → Bandeja de tareas y notificaciones.",
  "Hay una tarea de coordinación por tipo y una por producto, dirigidas a cargos (no a personas), con el contenido mínimo definido."),
 (6, "Resolver un ajuste de asignación como dirección",
  "En 02 Empresas y productos abra Alimentos del Norte S.A.; en el Tablero BI (En ajuste) use «Resolver ajuste». "
  "Pruebe las cuatro decisiones disponibles en el selector.",
  "Existen cuatro decisiones: aceptar la propuesta, mantener la fecha solicitada, contrapropuesta (sigue en ajuste) y "
  "devolver para reformulación. La decisión queda en el historial de la asignación y en la bitácora."),
 (6, "Resolver un ajuste de coordinación",
  "Si un coordinador propuso ajuste de su coordinación (04 Mis asignaciones → tarjeta de coordinación En ajuste), "
  "use «Resolver ajuste» como dirección.",
  "Solo la dirección (CEO/Gerente) puede resolverlo: aceptar la propuesta o devolver para reformulación, con motivo obligatorio."),
 (7, "Registrar una solicitud consolidada de requisitos",
  "En la ficha de un proyecto con requisitos definidos pulse «Solicitud consolidada» en la cabecera del proyecto.",
  "Una sola solicitud agrupa los requisitos de todos los productos, con fecha, medio, contacto, asistentes y evidencia; "
  "todos pasan a «Solicitado al cliente»."),
 (8, "Verificar los bloqueos del plan de trabajo",
  "En 05 Planes de trabajo pulse «Plan de trabajo · nueva versión» en un proyecto con alguna asignación pendiente o en ajuste.",
  "La aprobación se bloquea con el detalle de qué asignaciones faltan; con todo aceptado, el editor permite modificar horas y "
  "fechas de hitos y advierte si alguna fecha cae en festivo o fin de semana."),
 (9, "Consultar el dashboard con clics en los gráficos",
  "En 01 Dashboard haga clic en una porción del anillo de tipo, en un tramo de una barra de empresa y en la mini-leyenda de condición.",
  "Cada clic acota el tablero completo; la fila de distintivos muestra «N de M proyecto(s)» y «Limpiar todo» deshace."),
 (9, "Gestionar una alerta sin abrir la ficha",
  "En 03 Alertas use el botón de acción que acompaña a cualquier alerta (p. ej. «Resolver ajuste» o «Registrar respuesta»).",
  "El botón abre directamente el formulario que resuelve esa alerta, respetando permisos."),
 (10, "Verificar el cierre estricto de un producto",
  "Declare completado un producto que tenga un requisito «No recibido» o un proyecto sin plan final.",
  "La aplicación no lo cierra: la alerta «Completado sin poder cerrar» detalla qué falta (requisitos sin resolver, plan final aprobado, "
  "fecha real, horas o entregable)."),
 (11, "Verificar el cierre automático del proyecto maestro",
  "Consulte DEM-004 · Textiles del Sur (todos sus productos cerrados).",
  "El proyecto maestro está Cerrado automáticamente, con el consolidado de horas en la bitácora."),
 (12, "Parametrizar personas y cargos",
  "En 08 Parametrización → Personas y cargos revise las ocho filas.",
  "Los usuarios son los cargos mismos (nombre = cargo). Cuando la gerencia asigne titulares, basta cambiar el nombre de la fila."),
 (12, "Descargar y restaurar bases",
  "En 09 Bases y auditoría descargue el respaldo completo (JSON) y un conjunto CSV; use «Cargar base» para restaurar el JSON.",
  "Los ocho conjuntos descargan completos o filtrados; la restauración pide confirmación y no borra nada sin avisar."),
]),

"Gerente": dict(nombre="Gerente", responsabilidad=(
    "Gerencia. Puede generar nuevos proyectos (RN-01), resolver ajustes como dirección, "
    "parametrizar catálogos y tarifas, y controlar el portafolio."), filas=[
 (1, "Generar un nuevo proyecto como Gerente",
  "En sesión Gerente abra 07 Nuevo proyecto. Verifique vendedor, cargo y fecha bloqueados a la sesión. Complete la venta con al menos "
  "dos productos de categorías distintas, con horas, tarifas y fecha solicitada por producto.",
  "El registro exige fecha solicitada en cada producto; sin ella la validación «Fecha solicitada por producto» bloquea la activación."),
 (3, "Probar la validación de duplicados",
  "Registre una venta con la misma empresa y el mismo PPR de un proyecto activo existente.",
  "La validación de duplicidad advierte el registro equivalente antes de activar."),
 (4, "Verificar la asignación por cargo",
  "Active el proyecto y revise en el paso 4 la tabla «Asignaciones que generará el motor».",
  "Cada producto queda asignado al cargo que dicta la regla (mediciones → Director de Proyectos, BI → Gestor de Datos 1, "
  "cápsulas → Supervisor Contactabilidad, diseño → Diseñador) y la coordinación al cargo del tipo."),
 (6, "Devolver un ajuste para reformulación",
  "En un producto En ajuste use «Resolver ajuste» y elija «Devolver para reformulación» con motivo.",
  "La asignación vuelve a «Pendiente de aceptación», el líder puede reformular y cada ronda queda en el historial."),
 (6, "Hacer una contrapropuesta de fecha",
  "En un producto En ajuste elija «Contrapropuesta (sigue en ajuste)» con una fecha intermedia y motivo.",
  "La asignación sigue En ajuste con la nueva fecha propuesta por la dirección; el líder puede aceptarla."),
 (7, "Registrar la respuesta del cliente con pendientes",
  "En un producto con requisitos solicitados use «Registrar respuesta», marque «No recibido» y diligencie nueva fecha comprometida, "
  "responsable del seguimiento y próxima gestión.",
  "El pendiente queda con fecha compromiso; al vencerse, la alerta «Información pendiente del cliente» lo reporta como compromiso vencido."),
 (7, "Registrar dónde queda alojada la información recibida",
  "Registre otra respuesta como «Recibido» indicando la ubicación (carpeta, enlace o repositorio).",
  "La ubicación queda en el requisito como confirmación del recibido a satisfacción."),
 (8, "Aprobar un plan con horas ajustadas",
  "En el editor del plan modifique las horas de un producto y apruebe con motivo.",
  "Las horas del producto se actualizan, el cambio queda en bitácora y el plan crea una versión nueva."),
 (8, "Comparar plan de venta contra plan final",
  "En 05 Planes de trabajo revise la tabla «Plan de venta frente a plan final» de DEM-001.",
  "Por producto se ven las fechas de venta, las del plan final, la diferencia en días resaltada y las horas; "
  "los compromisos del cliente y de Rehavid aparecen en la misma tarjeta."),
 (9, "Controlar el portafolio desde el dashboard",
  "Use los filtros y los clics en gráficos para acotar por empresa y condición; abra la ficha de una empresa desde la barra.",
  "El tablero completo responde a cada clic y la ficha de la empresa muestra todos sus proyectos y productos."),
 (9, "Gestionar alertas con acción directa",
  "En 03 Alertas filtre por cargo responsable y use los botones de acción de las alertas.",
  "El filtro poda las filas a ese cargo; cada alerta ofrece el botón de la acción que la resuelve."),
 (10, "Corregir datos de cierre bloqueados",
  "En un producto «Completado sin poder cerrar» use «Completar el cierre» desde la alerta y resuelva lo que falte "
  "(p. ej. exceptuar un requisito con justificación).",
  "Con todo resuelto la aplicación cierra el producto automáticamente y lo registra en bitácora."),
 (11, "Consolidar el cierre del proyecto maestro",
  "Cierre el último producto abierto de un proyecto de prueba.",
  "El proyecto maestro pasa a Cerrado sin acción manual y el toast lo anuncia."),
 (12, "Parametrizar productos y tarifas",
  "En 08 Parametrización edite horas y valor hora de un producto del catálogo y regístrelo en una venta nueva.",
  "La venta carga las horas y la tarifa parametrizadas como valores por defecto."),
 (12, "Auditar los cambios",
  "En 09 Bases y auditoría revise el historial de cambios de un proyecto trabajado hoy.",
  "Cada modificación conserva usuario (cargo), fecha, valor anterior, valor nuevo y motivo (RN-18)."),
]),

"Director de Proyectos": dict(nombre="Director de Proyectos", responsabilidad=(
    "Coordina los proyectos Tipo 2, lidera las mediciones objetivas y puede generar nuevos proyectos (RN-01)."), filas=[
 (1, "Generar un nuevo proyecto como Director",
  "En sesión Director de Proyectos abra 07 Nuevo proyecto y registre una venta Tipo 2 con un producto de medición objetiva "
  "(tecnología obligatoria) y fecha solicitada.",
  "El Director puede vender; el vendedor queda bloqueado a su sesión y la tecnología es obligatoria para mediciones."),
 (4, "Recibir la coordinación Tipo 2 como asignación propia",
  "Active el proyecto y abra 04 Mis asignaciones.",
  "Aparece una tarjeta «Coordinación Tipo 2 · [código]» independiente de las de producto, con estado «Pendiente de aceptación», "
  "plan estimado, contacto principal y fecha de referencia."),
 (6, "Aceptar la asignación de coordinación",
  "En la tarjeta de coordinación pulse «Aceptar coordinación» declarando capacidad.",
  "La coordinación pasa a Aceptada con fecha, usuario y capacidad; la aceptación queda en su historial y no depende de ningún producto."),
 (6, "Proponer ajuste de la coordinación",
  "En otra coordinación pendiente use «Proponer ajuste» con fecha propuesta, capacidad y justificación.",
  "La coordinación queda En ajuste; solo la dirección puede resolverla y cada ronda queda en el historial."),
 (6, "Aceptar la asignación del producto de mediciones",
  "En 04 Mis asignaciones acepte la asignación de mediciones declarando tiempo requerido de producción, capacidad e inicio/fecha objetivo.",
  "La asignación pasa a Aceptada, el producto queda Programado y la aceptación queda en el historial."),
 (6, "Proponer un ajuste con justificación y recibir la decisión",
  "Proponga un ajuste de fecha en un producto propio; pida a la dirección resolverlo con contrapropuesta o devolución.",
  "El ajuste queda En ajuste; si la dirección contrapropone sigue En ajuste con la nueva fecha; si lo devuelve, vuelve a Pendiente. "
  "Todas las rondas quedan en el historial de la asignación."),
 (7, "Definir los requisitos de información de mediciones",
  "En la tarjeta del producto use «Requisitos de información» (o «Definir requisitos» si está vacío) y agregue dos requisitos.",
  "Los requisitos quedan «Definido» con su autor; la tarjeta muestra el conteo de recibidos y pendientes."),
 (7, "Consolidar los requisitos del proyecto en una sola solicitud",
  "En la cabecera del proyecto pulse «Solicitud consolidada»; registre fecha, medio (reunión/llamada/correo), contacto, asistentes y evidencia.",
  "Los requisitos definidos de TODOS los productos pasan a «Solicitado al cliente» en una sola gestión, registrada a nivel del proyecto."),
 (7, "Registrar la respuesta y el seguimiento de pendientes",
  "Registre una respuesta «No recibido» con nueva fecha comprometida, responsable del seguimiento y próxima gestión; "
  "y una «Recibido» con la ubicación de la información.",
  "El pendiente genera alerta al vencerse la fecha comprometida; lo recibido queda con su ubicación como constancia."),
 (8, "Construir el plan de trabajo final con bloqueos",
  "Pulse «Construir plan de trabajo» con una asignación aún en ajuste; luego resuélvala y vuelva a intentar.",
  "El primer intento se bloquea listando las asignaciones sin resolver; el segundo permite aprobar con fechas, horas e hitos editables."),
 (8, "Versionar el plan y comparar contra la venta",
  "Cree una nueva versión moviendo la fecha de un hito, con motivo; revise la tabla «Plan de venta frente a plan final» y el historial.",
  "La versión anterior se conserva; la comparación muestra la diferencia en días por producto; el historial detalla quién aprobó cada versión."),
 (8, "Verificar la advertencia de calendario",
  "Apruebe un plan con una fecha en sábado, domingo o festivo de Colombia.",
  "La aplicación advierte el choque (sin bloquear) indicando producto, hito y motivo."),
 (9, "Registrar avance con el botón propio",
  "En la tarjeta de mediciones use «Registrar avance» (no «Registrar novedad»).",
  "El formulario abre con el tipo Avance preseleccionado; horas y avance se actualizan en la tarjeta."),
 (9, "Registrar un Bloqueo",
  "Use «Registrar novedad» y elija el tipo «Bloqueo» con causa, acción, responsable y nueva fecha.",
  "El tipo Bloqueo existe y exige los cuatro campos; el estado del producto no cambia y la novedad queda en la línea de tiempo."),
 (9, "Actualizar los hitos directamente",
  "Use «Actualizar hitos» y cambie porcentaje, fecha y horas de un hito.",
  "El avance global del producto se recalcula desde los hitos y el cambio queda en bitácora."),
 (9, "Registrar la próxima acción",
  "Use el botón «Próxima acción» con descripción, fecha y responsable.",
  "La próxima acción aparece en la tarjeta y en el calendario."),
 (10, "Declarar completado con cierre estricto",
  "Declare completado el producto con fecha real, horas y entregable, dejando un requisito sin resolver a propósito.",
  "La aplicación NO cierra: la validación exige todo requisito recibido o exceptuado y plan final aprobado. Al resolverlo, cierra automáticamente."),
 (11, "Verificar el cierre del proyecto maestro Tipo 2",
  "Cierre todos los productos de un proyecto de prueba.",
  "El maestro pasa a Cerrado automáticamente con el consolidado en bitácora."),
]),

"Jefe de Operaciones": dict(nombre="Jefe de Operaciones", responsabilidad=(
    "Coordina los proyectos Tipo 1, lidera el acompañamiento técnico y puede generar nuevos proyectos (RN-01)."), filas=[
 (1, "Generar un nuevo proyecto como Jefe de Operaciones",
  "En sesión Jefe de Operaciones registre una venta Tipo 1 completa en 07 Nuevo proyecto.",
  "El Jefe de Operaciones está autorizado para vender (RN-01); vendedor, cargo y fecha quedan bloqueados a su sesión."),
 (4, "Recibir la coordinación Tipo 1 pendiente",
  "Abra 04 Mis asignaciones en sesión Jefe de Operaciones.",
  "La coordinación Tipo 1 de DEM-002 aparece como tarjeta «Pendiente de aceptación» (la base demostrativa la trae pendiente para esta prueba)."),
 (6, "Aceptar la asignación de coordinación",
  "Pulse «Aceptar coordinación» en la tarjeta de DEM-002, declarando capacidad.",
  "La coordinación pasa a Aceptada con registro de fecha, usuario y capacidad, y el contador de la pestaña baja."),
 (6, "Resolver los ajustes de los líderes con cuatro decisiones",
  "Provoque un ajuste en un producto Tipo 1 (o use DEM-001 como dirección) y pruebe «Devolver para reformulación» con comentario.",
  "Existe la opción de devolver con comentario: la asignación vuelve al líder en «Pendiente de aceptación» y la ronda queda en el historial."),
 (7, "Consolidar los requisitos de los líderes",
  "En la cabecera del proyecto use «Solicitud consolidada» para agrupar los requisitos de todos los productos.",
  "Una única solicitud al cliente con fecha, responsable, medio y evidencia reemplaza las gestiones producto por producto."),
 (7, "Registrar la respuesta con nueva fecha comprometida",
  "Registre una respuesta «No recibido» con fecha comprometida por el cliente y responsable del seguimiento.",
  "El campo existe; al vencerse la fecha, la alerta reporta el compromiso vencido para el seguimiento."),
 (8, "Construir el plan Tipo 1 con hitos y compromisos",
  "Construya el plan final de DEM-002: fechas por producto, hitos editables, horas modificables y compromisos del cliente y de Rehavid.",
  "El editor permite fechas, horas e hitos; los compromisos quedan visibles en el plan vigente y en el módulo 05."),
 (8, "Versionar el plan moviendo fechas de hitos",
  "Cree una nueva versión cambiando la fecha de un hito directamente en el editor.",
  "Las fechas de los hitos son editables al versionar; la fecha original queda como línea base para medir la desviación."),
 (9, "Controlar el avance de todos los productos",
  "En la ficha de la empresa revise avance real contra esperado, horas ejecutadas, saldo y última actualización por producto.",
  "La tarjeta muestra el detalle completo; el proyecto muestra horas vendidas y ejecutadas para compararlas."),
 (9, "Suspender y reanudar con botones propios",
  "En un producto propio use el botón «Suspender» (causa, acción, responsable y fecha de revisión) y luego «Reanudar».",
  "Ambos botones existen y precargan el tipo correspondiente; la suspensión exige los campos de RN-15."),
 (9, "Gestionar alertas sin abrir la ficha",
  "En 03 Alertas use el botón de acción directa de una alerta de sus proyectos.",
  "La alerta se gestiona desde el módulo: el botón abre el formulario exacto que la resuelve."),
 (9, "Registrar una novedad desde el calendario",
  "En 06 Calendario abra un día con eventos de un producto propio y use «Registrar novedad».",
  "El detalle del día permite reprogramar o registrar novedad sin salir del calendario."),
 (9, "Filtrar el calendario por líder",
  "En 06 Calendario filtre por cargo responsable.",
  "Solo quedan los eventos de los productos de ese cargo."),
 (10, "Verificar el cierre automático de un producto",
  "Declare completado un producto propio con todo resuelto.",
  "El producto pasa a Cerrado sin acción manual; fecha real, horas y entregable quedan registrados."),
 (11, "Verificar el cierre del maestro con horas comparadas",
  "Al cerrarse todos los productos, revise el proyecto y su bitácora.",
  "El maestro cierra automáticamente y la bitácora consolida horas ejecutadas frente a vendidas."),
 (12, "Descargar el seguimiento filtrado",
  "En 09 Bases y auditoría descargue el conjunto Seguimiento con el filtro de empresa aplicado.",
  "La descarga refleja el corte visible; incluye novedades, retrasos, suspensiones y alertas."),
 (12, "Verificar el bloqueo de venta a cargos no autorizados",
  "Cambie la sesión a Diseñador o Gestor de Datos 1 e intente abrir 07 Nuevo proyecto.",
  "El módulo se bloquea explicando que solo CEO, Gerente, Jefe de Operaciones y Director de Proyectos pueden registrar ventas."),
]),

"Supervisor Contactabilidad": dict(nombre="Supervisor Contactabilidad", responsabilidad=(
    "Lidera las cápsulas formativas: acepta la asignación, gestiona insumos, grabación, avance y cierre."), filas=[
 (4, "Revisar la asignación de cápsulas",
  "En sesión Supervisor Contactabilidad abra 04 Mis asignaciones con el rol propio seleccionado.",
  "Aparecen las cápsulas asignadas con horas vendidas y, si se registró, las personas a impactar."),
 (6, "Aceptar la asignación de cápsulas",
  "Acepte la asignación declarando tiempo requerido y capacidad.",
  "La asignación pasa a Aceptada y queda en el historial."),
 (6, "Proponer ajuste de fecha con justificación",
  "En una asignación pendiente proponga otra fecha justificando con la disponibilidad de producción de contenidos.",
  "El ajuste queda En ajuste para resolución de la coordinación, con la justificación registrada."),
 (7, "Definir los insumos de las cápsulas",
  "Use «Requisitos de información» para registrar los insumos (temas, material de apoyo, matrices, validación SST).",
  "Los insumos quedan como requisitos definidos, listos para la solicitud centralizada del coordinador."),
 (7, "Verificar que la solicitud la centraliza la coordinación",
  "Intente «Solicitar al cliente» desde su tarjeta y observe el permiso.",
  "La solicitud corresponde a la coordinación; el supervisor define, la coordinación solicita (RN-11)."),
 (8, "Confirmar las fechas de grabación en el plan",
  "Revise en el plan de trabajo del proyecto las fechas de sus cápsulas; si no son viables, proponga ajuste o registre novedad.",
  "Las fechas del plan final rigen la grabación; los cambios crean versión nueva con motivo."),
 (9, "Revisar la disponibilidad en el calendario",
  "En 06 Calendario filtre por su cargo y revise las fechas de grabación y entrega.",
  "El calendario muestra solo sus eventos, con festivos de Colombia visibles."),
 (9, "Registrar avance de las cápsulas",
  "Use «Registrar avance» al completar la producción de una cápsula, actualizando horas.",
  "El avance y las horas quedan en la tarjeta; el estado pasa a En ejecución."),
 (9, "Registrar personas a impactar",
  "En la ficha del proyecto (o al registrar la venta) diligencie «Personas a impactar» del producto de cápsulas.",
  "El campo existe para cápsulas, se ve en la tarjeta junto a las horas y sale en el conjunto descargable de productos."),
 (9, "Registrar una reprogramación de grabación",
  "Use «Registrar novedad» tipo Reprogramación con causa, acción, responsable y nueva fecha.",
  "La reprogramación desplaza la fecha objetivo y los hitos pendientes, conservando la línea base."),
 (9, "Comprobar que solo actualiza su producto",
  "Intente registrar avance en un producto de otro cargo.",
  "Los botones aparecen deshabilitados explicando de quién es la responsabilidad."),
 (9, "Revisar sus alertas",
  "En 03 Alertas filtre por su cargo.",
  "Solo aparecen las filas de sus productos, con el botón de la acción que resuelve cada alerta."),
 (10, "Cargar el entregable y declarar completado",
  "Declare completado con fecha real, horas y el entregable (curso cargado / CSV de consumo).",
  "Con requisitos resueltos y plan aprobado, el producto cierra automáticamente."),
 (11, "Consultar el estado del proyecto maestro",
  "Revise la ficha del proyecto al cerrar sus cápsulas.",
  "El avance consolidado refleja el cierre; si todos los productos cierran, el maestro cierra solo."),
]),

"Gestor de Datos 1": dict(nombre="Gestor de Datos 1", responsabilidad=(
    "Lidera el Tablero BI: acepta la asignación, define requisitos de datos, ejecuta y cierra."), filas=[
 (4, "Revisar la asignación del tablero BI",
  "En sesión Gestor de Datos 1 abra 04 Mis asignaciones.",
  "El Tablero BI aparece asignado a su cargo, con el resumen Pendientes · En ajuste · Aceptadas arriba."),
 (6, "Aceptar la asignación del tablero",
  "Acepte declarando tiempo requerido, capacidad e inicio/fecha objetivo.",
  "La asignación pasa a Aceptada; sin fechas comprometidas el producto sigue Pendiente de información."),
 (6, "Proponer ajuste y recibir contrapropuesta",
  "Proponga un ajuste de fecha; pida a la dirección responder con contrapropuesta.",
  "La contrapropuesta llega con la fecha de la dirección y la asignación sigue En ajuste hasta aceptarla; todo queda en el historial."),
 (7, "Definir los requisitos de datos",
  "Registre los requisitos del tablero (accesos, diccionarios, históricos).",
  "Quedan definidos con autor y fecha, listos para la solicitud del coordinador."),
 (7, "Registrar dónde queda alojada la información",
  "Cuando llegue una respuesta, regístrela como «Recibido» con la ubicación (repositorio, carpeta, enlace).",
  "La ubicación queda como constancia del recibido a satisfacción."),
 (8, "Confirmar las fechas del tablero en el plan",
  "Revise el plan del proyecto; si la fecha no es viable, proponga ajuste antes de la aprobación.",
  "El plan no puede aprobarse con su asignación en ajuste: el sistema lo bloquea hasta resolverla."),
 (9, "Registrar avance con el botón propio",
  "Use «Registrar avance» actualizando porcentaje y horas ejecutadas.",
  "El avance queda en la tarjeta con la fecha de actualización."),
 (9, "Registrar una novedad y la próxima acción",
  "Use «Registrar novedad» para un retraso (causa, acción, responsable, nueva fecha) y «Próxima acción» para el siguiente compromiso.",
  "Cada botón abre su formulario; el retraso desplaza fechas conservando la línea base y la próxima acción alimenta el calendario."),
 (9, "Comprobar que solo actualiza su producto",
  "Intente registrar avance en las mediciones del Director.",
  "Los botones están deshabilitados con la explicación del cargo responsable."),
 (9, "Revisar solo sus alertas",
  "En 03 Alertas filtre por cargo «Gestor de Datos 1».",
  "La tabla queda podada a sus productos; cada alerta trae su botón de acción directa."),
 (9, "Consultar su programación en el calendario",
  "En 06 Calendario filtre por su cargo.",
  "Solo aparecen sus eventos (la observación de la primera ronda quedó corregida)."),
 (12, "Descargar el seguimiento de sus productos",
  "En 09 Bases y auditoría aplique el filtro y descargue el conjunto Seguimiento.",
  "La descarga respeta el filtro aplicado; el botón «Cargar base» explica que restaura un respaldo JSON o actualiza con CSV."),
 (10, "Cargar el entregable y declarar completado",
  "Declare completado con fecha real, horas y el enlace del tablero publicado.",
  "Con requisitos resueltos y plan aprobado, el producto pasa a Cerrado automáticamente."),
 (10, "Registrar una observación tras el cierre",
  "En el producto cerrado use «Registrar observación».",
  "La observación queda en la bitácora y la línea de tiempo sin modificar el estado Cerrado (observación de la primera ronda aplicada)."),
 (11, "Consultar el estado del proyecto maestro",
  "Revise la ficha del proyecto con su producto cerrado.",
  "El consolidado del maestro refleja el cierre; el proyecto cierra solo cuando todos los productos cierren."),
 (12, "Verificar que no puede generar proyectos",
  "Intente abrir 07 Nuevo proyecto.",
  "El módulo se bloquea: su cargo no está autorizado para registrar ventas (RN-01)."),
]),

"Gestor de Datos 2": dict(nombre="Gestor de Datos 2", responsabilidad=(
    "Cargo gemelo de datos, sin asignaciones por regla: recibe trabajo por reasignación de la coordinación."), filas=[
 (4, "Verificar el estado vacío de Mis asignaciones",
  "En sesión Gestor de Datos 2 abra 04 Mis asignaciones.",
  "La pantalla muestra un estado vacío claro («Sin asignaciones para este rol») con la opción de cambiar el rol o limpiar filtros, "
  "sin mostrar asignaciones de otros cargos."),
 (6, "Recibir un producto por reasignación",
  "Pida a la dirección reasignar el Tablero BI a «Gestor de Datos 2» («Reasignar cargo» en la tarjeta, con motivo).",
  "Llega una tarea nueva a su cargo, la asignación vuelve a «Pendiente de aceptación» y el cambio queda en bitácora."),
 (6, "Aceptar la asignación reasignada",
  "Acepte la asignación recibida declarando tiempo y capacidad.",
  "El producto queda a su cargo, con su cargo como responsable en la tarjeta."),
 (9, "Actualizar el producto recibido",
  "Registre un avance con horas en el producto reasignado.",
  "Solo su cargo (o la dirección) puede actualizarlo; el avance queda registrado a su nombre de cargo."),
 (9, "Comprobar el bloqueo sobre productos ajenos",
  "Intente registrar novedades en productos de otros cargos.",
  "Los botones aparecen deshabilitados con la razón del bloqueo."),
 (9, "Revisar alertas y calendario de su cargo",
  "Filtre 03 Alertas y 06 Calendario por «Gestor de Datos 2».",
  "Ambos módulos quedan acotados a los productos de su cargo (vacíos si aún no tiene)."),
 (12, "Consultar el dashboard",
  "Recorra 01 Dashboard haciendo clic en gráficos y filtros.",
  "La consulta es libre: los clics acotan el tablero y «Limpiar todo» restaura."),
 (12, "Descargar un conjunto de datos",
  "Descargue el conjunto Productos desde 09 Bases y auditoría.",
  "La descarga funciona para cualquier cargo; la edición sigue restringida por permisos."),
 (12, "Verificar que no puede generar proyectos",
  "Intente abrir 07 Nuevo proyecto.",
  "El módulo se bloquea con la explicación de los cargos autorizados (RN-01)."),
]),

"Diseñador": dict(nombre="Diseñador", responsabilidad=(
    "Lidera los productos de diseño: acepta la asignación según complejidad, define insumos, ejecuta y cierra."), filas=[
 (4, "Encontrar su asignación con el selector Rol",
  "En sesión Diseñador abra 04 Mis asignaciones.",
  "El selector «Rol» llega preseleccionado con su cargo y el resumen muestra Pendientes · En ajuste · Aceptadas · Coordinación "
  "aunque haya ceros; su producto de diseño (DEM-003) aparece con el plan estimado y el contacto principal del proyecto."),
 (6, "Aceptar o ajustar la asignación de diseño",
  "Si está pendiente, acepte la asignación; si ya está aceptada, pruebe el flujo con una venta nueva de diseño hecha por la dirección.",
  "Los botones «Aceptar asignación» y «Proponer ajuste» aparecen en la tarjeta cuando la asignación está pendiente."),
 (6, "Proponer ajuste según la complejidad",
  "Proponga un ajuste justificando por complejidad del alcance (Baja/Media/Alta visible en la tarjeta).",
  "La complejidad es visible y la justificación queda en el historial de la negociación."),
 (7, "Definir los insumos del diseño",
  "En su tarjeta use el botón «Definir requisitos de información» (visible aunque no haya ninguno) y registre los insumos "
  "(planos, fichas técnicas, accesos).",
  "La sección de requisitos está siempre a la vista en la tarjeta; los insumos quedan definidos para la solicitud del coordinador."),
 (7, "Verificar que los insumos los solicita la coordinación",
  "Observe quién puede «Solicitar al cliente» y revise la fecha de solicitud cuando ocurra.",
  "La solicitud la centraliza la coordinación con fecha y evidencia; usted ve el estado de cada requisito en su tarjeta."),
 (8, "Confirmar las fechas del diseño en el plan de trabajo",
  "Abra 05 Planes de trabajo → botón destacado «Plan de trabajo» del proyecto de Metalúrgica; revise sus fechas. "
  "Si no son viables, proponga ajuste de su asignación o registre una novedad.",
  "El botón del plan se llama «Plan de trabajo», resalta en morado, y sus fechas se contrastan contra el plan de venta."),
 (9, "Registrar avance con el botón propio",
  "En su tarjeta use «Registrar avance».",
  "Existe un botón propio (ya no se confunde con «Registrar respuesta», que es solo de requisitos); avance y horas se actualizan."),
 (9, "Registrar una novedad",
  "Use el botón «Registrar novedad» para un retraso con causa, acción, responsable y nueva fecha.",
  "El botón existe junto a «Registrar avance»; el retraso desplaza fechas conservando la línea base."),
 (9, "Registrar la próxima acción",
  "Use el botón «Próxima acción».",
  "Existe un botón propio con descripción, fecha y responsable; alimenta la tarjeta y el calendario."),
 (9, "Reanudar el diseño suspendido",
  "En DEM-003 (suspendido) use el botón «Reanudar».",
  "El botón Reanudar aparece en los productos suspendidos y precarga el tipo Reanudación."),
 (9, "Actualizar hitos del diseño",
  "Use «Actualizar hitos» para registrar el porcentaje de la propuesta de diseño.",
  "Cada hito admite porcentaje, fecha y horas; el avance global se recalcula."),
 (9, "Registrar una validación intermedia con el cliente",
  "Use «Registrar novedad» tipo Nota describiendo la validación intermedia.",
  "La validación queda en la línea de tiempo del producto como parte del seguimiento."),
 (9, "Comprobar que solo actualiza su producto",
  "Intente actualizar el Tablero BI del mismo proyecto.",
  "Los botones están deshabilitados con la explicación del cargo responsable."),
 (9, "Revisar sus alertas",
  "En 03 Alertas filtre por «Diseñador».",
  "Solo sus filas aparecen, cada una con el botón de acción directa (p. ej. «Reanudar» sobre la alerta de suspensión)."),
 (12, "Verificar que no puede generar proyectos",
  "Intente abrir 07 Nuevo proyecto.",
  "El módulo se bloquea explicando los cargos autorizados (RN-01)."),
]),
}

# --- Pestaña 1 · Mapa de usuario: (paso, rol, qué hace, módulo, produce, necesita) ---
MAPA = []
def _m(paso, rol, hace, modulo, produce, necesita):
    MAPA.append((paso, rol, hace, modulo, produce, necesita))

for rol in ["CEO", "Gerente", "Director de Proyectos", "Jefe de Operaciones"]:
    _m(1, rol, "Registra la venta con vendedor, cargo y fecha bloqueados a su sesión; productos con horas, tarifa y fecha solicitada; contactos del cliente.",
       "07 Nuevo proyecto", "Proyecto maestro en borrador con productos y contactos", "Estar en sesión con un cargo autorizado (RN-01); catálogo de empresas, PPR y productos parametrizado")
    _m(3, rol, "Supera las 14 validaciones (catálogo, fechas solicitadas, contactos, horas, tecnología, complejidad, duplicados) y activa.",
       "07 Nuevo proyecto · paso 4", "Proyecto Activo; asignaciones y tareas generadas por cargo", "Todos los datos obligatorios de la venta")
_m(4, "Director de Proyectos", "Recibe la coordinación Tipo 2 como asignación propia con ciclo Pendiente · En ajuste · Aceptada.",
   "04 Mis asignaciones", "Coordinación aceptada o ajuste propuesto, con historial", "Proyecto Tipo 2 activo")
_m(4, "Jefe de Operaciones", "Recibe la coordinación Tipo 1 como asignación propia (en la demo, DEM-002 llega pendiente).",
   "04 Mis asignaciones", "Coordinación aceptada o ajuste propuesto, con historial", "Proyecto Tipo 1 activo")
for rol, prod in [("Director de Proyectos", "mediciones objetivas"), ("Gestor de Datos 1", "Tablero BI"),
                  ("Supervisor Contactabilidad", "cápsulas"), ("Diseñador", "diseño")]:
    _m(6, rol, f"Acepta la asignación de {prod} contrastando fecha solicitada, tiempo requerido y capacidad; o propone ajuste justificado.",
       "04 Mis asignaciones · tarjeta del producto", "Asignación Aceptada o En ajuste, con historial de rondas", "Tarea de asignación generada por el motor")
for rol in ["CEO", "Gerente"]:
    _m(6, rol, "Resuelve los ajustes propuestos: aceptar, mantener, contrapropuesta o devolver para reformulación; también los de coordinación.",
       "02 Empresas y productos · 04 Mis asignaciones", "Decisión registrada con motivo e historial", "Ajuste propuesto por un líder o coordinador")
for rol in ["Director de Proyectos", "Jefe de Operaciones"]:
    _m(7, rol, "Consolida los requisitos de todos los productos y registra UNA solicitud al cliente (fecha, medio, asistentes, evidencia); registra respuestas con ubicación o fecha comprometida.",
       "02 Empresas y productos · Solicitud consolidada", "Requisitos Solicitados; pendientes con compromiso y responsable", "Requisitos definidos por los líderes; contacto principal del cliente")
for rol, prod in [("Director de Proyectos", "mediciones"), ("Gestor de Datos 1", "el tablero"),
                  ("Supervisor Contactabilidad", "las cápsulas"), ("Diseñador", "el diseño")]:
    _m(7, rol, f"Define los requisitos de información de {prod} (datos, accesos, insumos, validaciones).",
       "Tarjeta del producto · Requisitos de información", "Requisitos Definidos con autor y fecha", "Asignación aceptada")
for rol in ["Director de Proyectos", "Jefe de Operaciones"]:
    _m(8, rol, "Construye y versiona el plan de trabajo final: fechas, horas e hitos editables; compromisos de ambas partes; bloqueado si hay asignaciones sin resolver; advierte festivos.",
       "05 Planes de trabajo", "Plan final versionado como referencia obligatoria (RN-13, RN-14)", "Asignaciones aceptadas y fechas negociadas")
for rol in ["Director de Proyectos", "Jefe de Operaciones", "Supervisor Contactabilidad", "Gestor de Datos 1", "Gestor de Datos 2", "Diseñador"]:
    _m(9, rol, "Ejecuta su producto: registra avance, novedades (incluido Bloqueo), suspende/reanuda, actualiza hitos y próxima acción; solo sobre sus productos.",
       "02 Empresas y productos · tarjeta del producto", "Panel actualizado: avance, horas, fechas, línea de tiempo", "Ser el cargo responsable del producto (RN-12)")
for rol in ["Director de Proyectos", "Jefe de Operaciones", "Supervisor Contactabilidad", "Gestor de Datos 1", "Gestor de Datos 2", "Diseñador"]:
    _m(10, rol, "Declara el producto completado con fecha real, horas y entregable; la aplicación valida (requisitos resueltos + plan aprobado) y cierra.",
       "Tarjeta del producto · Declarar completado", "Producto Cerrado automáticamente, o alerta con lo que falta", "Requisitos recibidos o exceptuados; plan final aprobado")
for rol in ["CEO", "Gerente"]:
    _m(11, rol, "Verifica el cierre automático del proyecto maestro y el consolidado de horas.",
       "02 Empresas y productos · bitácora", "Proyecto maestro Cerrado con consolidado", "Todos los productos cerrados")
for rol in ["CEO", "Gerente"]:
    _m(12, rol, "Parametriza productos y tarifas, PPR, empresas, órdenes, personas/cargos, reglas del motor y acuerdos de servicio.",
       "08 Parametrización", "Catálogos y reglas vigentes", "Permiso de parametrización")
for rol in ["CEO", "Gerente", "Director de Proyectos", "Jefe de Operaciones", "Supervisor Contactabilidad", "Gestor de Datos 1", "Gestor de Datos 2", "Diseñador"]:
    _m(12, rol, "Consulta el dashboard interactivo (clic en gráficos), las alertas con acción directa y el calendario filtrado; descarga los conjuntos de datos.",
       "01 Dashboard · 03 Alertas · 06 Calendario · 09 Bases", "Lectura del portafolio y descargas", "Ninguno: la consulta es libre para todos los cargos")
